apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dbbo7b6bf-java-quarkus
  janus-idp.io/tekton: dbbo7b6bf-java-quarkus
  backstage.io/kubernetes-id: dbbo7b6bf-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dbbo7b6bf-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
